hibernate:
    format_sql: true
    use_sql_comments: true

---
grails:
    databinding:
        # 空文字は空文字、nullはnullとして扱う
        convertEmptyStringsToNull: false
        # 前後の半角スペースのトリムはする
        trimStrings: true
