hibernate:
    format_sql: true
    use_sql_comments: true

---
grails:
    databinding:
        convertEmptyStringsToNull: false
        trimStrings: true

---
grails:
    controller:
        maxDefault: 10
        maxLimit: 100
