hibernate:
    format_sql: true
    use_sql_comments: true

---
grails:
    databinding:
        convertEmptyStringsToNull: false
        trimStrings: true
        dateFormats:
            - yyyy/MM/dd HH:mm:ss
            - yyyy/MM/dd HH:mm
            - yyyy/MM/dd
            - yyyy-MM-dd HH:mm:ss
            - yyyy-MM-dd HH:mm
            - yyyy-MM-dd

---
grails:
    controller:
        maxDefault: 10
        maxLimit: 100
